build_settings:
    ignore:
        - "spec"
        - "includes"
        - "bin"

setup:
    shell:
        command:
            - "git clone https://github.com/luisabarca/wordpress-test-template.git wp-tests"
            - "bash wp-tests/bin/install-wp-tests.sh test root '' localhost latest"

test:
    php_mess_detector:
        allow_failures: true
    php_code_sniffer:
        standard: "./codesniffer.ruleset.xml"
        allow_failures: 10
#    php_cpd:
#        allow_failures: false
    php_loc:
        allow_failures: true
    php_unit:
        directory:
            - "tests/"

failure:
    slack_notify:
        webhook_url: "https://hooks.slack.com/services/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"
        room: "#notifications"
        username: "PHPCI"
        icon: ":ghost:"
        message: "%PROJECT_TITLE% - build %BUILD% failed! :angry:"
        show_status: false

success:
    slack_notify:
        webhook_url: "https://hooks.slack.com/services/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"
        room: "#notifications"
        username: "PHPCI"
        icon: ":ghost:"
        message: "%PROJECT_TITLE% - build %BUILD% succeeded! :smiley:"
        show_status: false

#    package_build:
#        directory: "./builds/"
#        filename: "category-pages-shortcodes-latest"
#        format: zip

complete:
    slack_notify:
        webhook_url: "https://hooks.slack.com/services/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"
        room: "#notifications"
        username: "PHPCI"
        icon: ":ghost:"
        message: "%PROJECT_TITLE% - build %BUILD% completed"
        show_status: true
