build_settings:
    ignore:
        - "spec"
        - "includes"
        - "bin"

setup:

test:
    php_mess_detector:
        allow_failures: true
    php_code_sniffer:
        standard: "./codesniffer.ruleset.xml"
        allow_failures: 10
#    php_cpd:
#        allow_failures: false
    php_loc:
        allow_failures: true
    php_unit:
        directory:
            - "tests/"

#success:
#    package_build:
#        directory: "./builds/"
#        filename: "category-pages-shortcodes-latest"
#        format: zip
