# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

pipelines:
  default:
    - step:
        script:
          # Update apt-get packages
          - apt-get update

          # Install the required packages for the running CI tests
          - apt-get -yqqf install vim git wget zip unzip subversion mysql-client libmcrypt-dev libmysqlclient-dev --fix-missing

          # Install mysql driver
          - docker-php-ext-install mysqli pdo_mysql mbstring

          # Install Xdebug
          - pecl install xdebug

          # PHP extensions
          - docker-php-ext-enable mysqli pdo_mysql mbstring xdebug

          # Install WP test suite
          - bash bin/install-wp-tests.sh test root 'test' 127.0.0.1 latest true

          # Download composer
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          # - composer install

          # Install PHP Unit
          - composer require phpunit/phpunit

          # Download PHP CodeSniffer and WP Coding Standards
          - composer require "squizlabs/php_codesniffer=*"
          #- git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
          - git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR

          # Set PHP CS standards
          - vendor/bin/phpcs --config-set installed_paths $SNIFFS_DIR

          # Check coding standards
          - vendor/bin/phpcs --extensions=php --report=summary --standard=./codesniffer.ruleset.xml .

          # Run uni tests
          - vendor/bin/phpunit
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql
      environment:
        MYSQL_DATABASE: test
        MYSQL_ROOT_PASSWORD: 'test'
